modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/complete-compost/issues"
[[mods]] #mandator
modId="complete_compost" #mandatory
version="1.0.2" #mandatory
displayName="Complete Compost" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/complete-compost/" #optional
logoFile="pack.png" # Named so it also shows up as the mods datapacks icon
credits="Thanks to Eninj for helping with design decisions"
authors="ChiefArug"
description='''
A mod about compost.
That's it.
Plants go brrrrr
'''
# Dependencies
[[dependencies.complete_compost]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.complete_compost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
